plugins {
    id 'java-library'
}

dependencies {
    api project(':alcoholic-api')
    api project(':domain')
    api project(':platform-api')

    testImplementation project(':integration-test-addon')

    testImplementation platform("org.junit:junit-bom:${junit_version}")
    testImplementation 'org.junit.jupiter:junit-jupiter'
}
