plugins {
    id 'java-library'
}

processTestResources {
    from('../minecraft-common/src/main/resources') {
        include 'data/alcoholic/alcoholic/quality/*.json'
    }
}

dependencies {
    api project(':alcoholic-api')
    api project(':domain')
    api project(':platform-api')

    testImplementation project(':integration-test-addon')

    testImplementation platform("org.junit:junit-bom:${junit_version}")
    testImplementation 'org.junit.jupiter:junit-jupiter'
}
