package com.djden.alcoholic.minecraft.content;

import com.djden.alcoholic.platform.api.registry.RegistryRef;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.entity.BlockEntityType;

public record IndustrialContent(
        RegistryRef<Block> industrialCasing,
        RegistryRef<Item> industrialCasingItem,
        RegistryRef<Block> machineWindow,
        RegistryRef<Item> machineWindowItem,
        RegistryRef<Block> accessHatch,
        RegistryRef<Item> accessHatchItem,
        RegistryRef<Block> fluidPort,
        RegistryRef<Item> fluidPortItem,
        RegistryRef<BlockEntityType<?>> fluidPortEntity,
        RegistryRef<Block> itemPort,
        RegistryRef<Item> itemPortItem,
        RegistryRef<BlockEntityType<?>> itemPortEntity,
        RegistryRef<Block> kineticPort,
        RegistryRef<Item> kineticPortItem,
        RegistryRef<BlockEntityType<?>> kineticPortEntity,
        RegistryRef<Block> pressController,
        RegistryRef<Item> pressControllerItem,
        RegistryRef<BlockEntityType<?>> pressControllerEntity,
        RegistryRef<Block> vatController,
        RegistryRef<Item> vatControllerItem,
        RegistryRef<BlockEntityType<?>> vatControllerEntity,
        RegistryRef<Block> tankController,
        RegistryRef<Item> tankControllerItem,
        RegistryRef<BlockEntityType<?>> tankControllerEntity,
        RegistryRef<Block> maltHouseController,
        RegistryRef<Item> maltHouseControllerItem,
        RegistryRef<BlockEntityType<?>> maltHouseControllerEntity,
        RegistryRef<Block> rollerMillController,
        RegistryRef<Item> rollerMillControllerItem,
        RegistryRef<BlockEntityType<?>> rollerMillControllerEntity,
        RegistryRef<Block> mashTunController,
        RegistryRef<Item> mashTunControllerItem,
        RegistryRef<BlockEntityType<?>> mashTunControllerEntity,
        RegistryRef<Block> brewingKettleController,
        RegistryRef<Item> brewingKettleControllerItem,
        RegistryRef<BlockEntityType<?>> brewingKettleControllerEntity,
        RegistryRef<Block> conditioningVesselController,
        RegistryRef<Item> conditioningVesselControllerItem,
        RegistryRef<BlockEntityType<?>> conditioningVesselControllerEntity,
        RegistryRef<Block> agingVesselController,
        RegistryRef<Item> agingVesselControllerItem,
        RegistryRef<BlockEntityType<?>> agingVesselControllerEntity
) {
}
