plugins {
    id 'java-library'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

minecraft {
    mappings channel: mapping_channel, version: mapping_version
    copyIdeResources = true
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    api project(':alcoholic-api')
    api project(':domain')
    api project(':platform-api')
    api project(':application')

    testImplementation project(':integration-test-addon')

    testImplementation platform("org.junit:junit-bom:${junit_version}")
    testImplementation 'org.junit.jupiter:junit-jupiter'
}
